// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZarzadzaniePrzychodniaWeterynaryjna.Models;

#nullable disable

namespace ZarzadzaniePrzychodniaWeterynaryjna.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260531210517_DodaniePozycjiWizyty")]
    partial class DodaniePozycjiWizyty
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ZarzadzaniePrzychodniaWeterynaryjna.Models.Harmonogram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_rezerwacji");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("PlanowanaDataRozpoczecia")
                        .HasColumnType("datetime2")
                        .HasColumnName("Planowana_Data_Rozpoczęcia");

                    b.Property<DateTime?>("RzeczywistyCzasRozpoczecia")
                        .HasColumnType("datetime2")
                        .HasColumnName("Rzeczywisty_Czas_Rozpoczęcia");

                    b.Property<DateTime?>("RzeczywistyCzasZakonczenia")
                        .HasColumnType("datetime2")
                        .HasColumnName("Rzeczywisty_Czas_Zakończenia");

                    b.Property<string>("StatusWizyty")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Status_Wizyty");

                    b.Property<int>("SzacowanyCzasTrwania")
                        .HasColumnType("int")
                        .HasColumnName("Szacowany_czas_trwania");

                    b.Property<int>("ZwierzeId")
                        .HasColumnType("int")
                        .HasColumnName("id_zwierzęcia");

                    b.HasKey("Id");

                    b.HasIndex("ZwierzeId");

                    b.ToTable("Harmonogram", t =>
                        {
                            t.HasTrigger("trg_BlokadaKonfliktowCzasowych");

                            t.HasCheckConstraint("CHK_Czas_Rzeczywisty", "[Rzeczywisty_Czas_Rozpoczęcia] <= CURRENT_TIMESTAMP");

                            t.HasCheckConstraint("CHK_Czas_Zakon", "[Rzeczywisty_Czas_Zakończenia] >= [Rzeczywisty_Czas_Rozpoczęcia]");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("ZarzadzaniePrzychodniaWeterynaryjna.Models.Katalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_pozycji");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CenaEwidencyjna")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("Cena_Ewidencyjna");

                    b.Property<int>("CzasTrwaniaWMin")
                        .HasColumnType("int")
                        .HasColumnName("czas_trwania_w_min");

                    b.Property<string>("JednostkaMiary")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Jednostka_Miary");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Typ")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("VAT")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.ToTable("Katalog", t =>
                        {
                            t.HasCheckConstraint("CHK_Katalog_Cena", "[Cena_Ewidencyjna] >= 0");
                        });
                });

            modelBuilder.Entity("ZarzadzaniePrzychodniaWeterynaryjna.Models.PozycjaWizyty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_pozycji_wizyty");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CenaZastosowana")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("Cena_Zastosowana");

                    b.Property<decimal>("Ilosc")
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("Ilosc");

                    b.Property<int>("KatalogId")
                        .HasColumnType("int")
                        .HasColumnName("id_katalogu");

                    b.Property<decimal>("VATZastosowany")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("VAT_Zastosowany");

                    b.Property<int>("WizytaId")
                        .HasColumnType("int")
                        .HasColumnName("id_wizyty");

                    b.HasKey("Id");

                    b.HasIndex("KatalogId");

                    b.HasIndex("WizytaId");

                    b.ToTable("Pozycja_Wizyty", t =>
                        {
                            t.HasCheckConstraint("CHK_PozycjaWizyty_Cena", "[Cena_Zastosowana] >= 0");

                            t.HasCheckConstraint("CHK_PozycjaWizyty_Ilosc", "[Ilosc] > 0");
                        });
                });

            modelBuilder.Entity("ZarzadzaniePrzychodniaWeterynaryjna.Models.WizytaMedyczna", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_wizyty");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataWizyty")
                        .HasColumnType("datetime2")
                        .HasColumnName("Data_Wizyty");

                    b.Property<string>("OpisWywiadu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Opis_Wywiadu");

                    b.Property<int>("RezerwacjaId")
                        .HasColumnType("int")
                        .HasColumnName("id_rezerwacji");

                    b.Property<string>("Rozpoznanie")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Rozpoznanie");

                    b.Property<string>("Zalecenia")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Zalecenia");

                    b.HasKey("Id");

                    b.HasIndex("RezerwacjaId");

                    b.ToTable("Wizyta_Medyczna");
                });

            modelBuilder.Entity("ZarzadzaniePrzychodniaWeterynaryjna.Models.Wlasciciel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_właściciela");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataRejestracji")
                        .HasColumnType("datetime2")
                        .HasColumnName("Data_rejestracji");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Email");

                    b.Property<string>("Imie")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Imię");

                    b.Property<string>("NazwaFirmy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Nazwa_firmy");

                    b.Property<string>("Nazwisko")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Nazwisko");

                    b.Property<string>("Telefon")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("Telefon");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Telefon")
                        .IsUnique()
                        .HasFilter("[Telefon] IS NOT NULL");

                    b.ToTable("Właściciel", t =>
                        {
                            t.HasCheckConstraint("CHK_Wlasciciel_Dane", "([Imię] IS NOT NULL AND [Nazwisko] IS NOT NULL) OR [Nazwa_firmy] IS NOT NULL");
                        });
                });

            modelBuilder.Entity("ZarzadzaniePrzychodniaWeterynaryjna.Models.Zwierze", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_zwierzęcia");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataUrodzenia")
                        .HasColumnType("datetime2")
                        .HasColumnName("Data_Urodzenia");

                    b.Property<string>("Gatunek")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Gatunek");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Imię");

                    b.Property<string>("Plec")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("Płeć");

                    b.Property<string>("Rasa")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Rasa");

                    b.Property<decimal?>("Waga")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("waga");

                    b.Property<int>("WlascicielId")
                        .HasColumnType("int")
                        .HasColumnName("id_właściciela");

                    b.HasKey("Id");

                    b.HasIndex("WlascicielId");

                    b.ToTable("Zwierzę", t =>
                        {
                            t.HasCheckConstraint("CHK_Zwierze_Waga", "[waga] > 0");
                        });
                });

            modelBuilder.Entity("ZarzadzaniePrzychodniaWeterynaryjna.Models.Harmonogram", b =>
                {
                    b.HasOne("ZarzadzaniePrzychodniaWeterynaryjna.Models.Zwierze", "Zwierze")
                        .WithMany()
                        .HasForeignKey("ZwierzeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zwierze");
                });

            modelBuilder.Entity("ZarzadzaniePrzychodniaWeterynaryjna.Models.PozycjaWizyty", b =>
                {
                    b.HasOne("ZarzadzaniePrzychodniaWeterynaryjna.Models.Katalog", "Katalog")
                        .WithMany()
                        .HasForeignKey("KatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZarzadzaniePrzychodniaWeterynaryjna.Models.WizytaMedyczna", "Wizyta")
                        .WithMany("WykorzystaneUslugiILeki")
                        .HasForeignKey("WizytaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Katalog");

                    b.Navigation("Wizyta");
                });

            modelBuilder.Entity("ZarzadzaniePrzychodniaWeterynaryjna.Models.WizytaMedyczna", b =>
                {
                    b.HasOne("ZarzadzaniePrzychodniaWeterynaryjna.Models.Harmonogram", "Rezerwacja")
                        .WithMany()
                        .HasForeignKey("RezerwacjaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rezerwacja");
                });

            modelBuilder.Entity("ZarzadzaniePrzychodniaWeterynaryjna.Models.Zwierze", b =>
                {
                    b.HasOne("ZarzadzaniePrzychodniaWeterynaryjna.Models.Wlasciciel", "Wlasciciel")
                        .WithMany("Zwierzeta")
                        .HasForeignKey("WlascicielId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wlasciciel");
                });

            modelBuilder.Entity("ZarzadzaniePrzychodniaWeterynaryjna.Models.WizytaMedyczna", b =>
                {
                    b.Navigation("WykorzystaneUslugiILeki");
                });

            modelBuilder.Entity("ZarzadzaniePrzychodniaWeterynaryjna.Models.Wlasciciel", b =>
                {
                    b.Navigation("Zwierzeta");
                });
#pragma warning restore 612, 618
        }
    }
}
