// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZarzadzaniePrzychodniaWeterynaryjna.Models;

#nullable disable

namespace ZarzadzaniePrzychodniaWeterynaryjna.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ZarzadzaniePrzychodniaWeterynaryjna.Models.Wlasciciel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_właściciela");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataRejestracji")
                        .HasColumnType("datetime2")
                        .HasColumnName("Data_rejestracji");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Email");

                    b.Property<string>("Imie")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Imię");

                    b.Property<string>("NazwaFirmy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Nazwa_firmy");

                    b.Property<string>("Nazwisko")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Nazwisko");

                    b.Property<string>("Telefon")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("Telefon");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Telefon")
                        .IsUnique()
                        .HasFilter("[Telefon] IS NOT NULL");

                    b.ToTable("Właściciel", t =>
                        {
                            t.HasCheckConstraint("CHK_Wlasciciel_Dane", "([Imię] IS NOT NULL AND [Nazwisko] IS NOT NULL) OR [Nazwa_firmy] IS NOT NULL");
                        });
                });

            modelBuilder.Entity("ZarzadzaniePrzychodniaWeterynaryjna.Models.Zwierze", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_zwierzęcia");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataUrodzenia")
                        .HasColumnType("datetime2")
                        .HasColumnName("Data_Urodzenia");

                    b.Property<string>("Gatunek")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Gatunek");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Imię");

                    b.Property<string>("Plec")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("Płeć");

                    b.Property<string>("Rasa")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Rasa");

                    b.Property<decimal?>("Waga")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("waga");

                    b.Property<int>("WlascicielId")
                        .HasColumnType("int")
                        .HasColumnName("id_właściciela");

                    b.HasKey("Id");

                    b.HasIndex("WlascicielId");

                    b.ToTable("Zwierzę", t =>
                        {
                            t.HasCheckConstraint("CHK_Zwierze_Waga", "[waga] > 0");
                        });
                });

            modelBuilder.Entity("ZarzadzaniePrzychodniaWeterynaryjna.Models.Zwierze", b =>
                {
                    b.HasOne("ZarzadzaniePrzychodniaWeterynaryjna.Models.Wlasciciel", "Wlasciciel")
                        .WithMany("Zwierzeta")
                        .HasForeignKey("WlascicielId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wlasciciel");
                });

            modelBuilder.Entity("ZarzadzaniePrzychodniaWeterynaryjna.Models.Wlasciciel", b =>
                {
                    b.Navigation("Zwierzeta");
                });
#pragma warning restore 612, 618
        }
    }
}
